# Generated by Django 2.1.5 on 2019-01-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('date_time', models.DateTimeField()),
                ('contents', models.TextField()),
            ],
        ),
    ]
